/*
# AL-WAZN Phase 5: Messaging & Notifications

## Purpose
Creates a real-time messaging and notification system connected to the existing
collaboration system. Conversations are auto-created when a collaboration is
accepted. Messages flow between the traveler and sender. Notifications are
generated by database triggers for collaboration events and new messages.

## 1. Enum
- `notification_type`: collaboration_request | collaboration_accepted | collaboration_rejected | new_message

## 2. Table: conversations
- id (uuid PK)
- collaboration_id → collaborations.id (UNIQUE, ON DELETE CASCADE)
- traveler_id → profiles.id (ON DELETE CASCADE)
- sender_id → profiles.id (ON DELETE CASCADE)
- created_at, updated_at (timestamptz)
- last_message_at (timestamptz, nullable)
- Unique constraint on collaboration_id (one conversation per collaboration)
- traveler_id and sender_id must match the related collaboration (CHECK via trigger)

## 3. Table: messages
- id (uuid PK)
- conversation_id → conversations.id (ON DELETE CASCADE)
- sender_id → profiles.id (ON DELETE CASCADE)
- message_text (text, NOT NULL, 1-2000 chars)
- created_at, updated_at (timestamptz)
- read_at (timestamptz, nullable)
- sender_id and conversation_id are immutable after creation (trigger)
- created_at is immutable after creation (trigger)

## 4. Table: notifications
- id (uuid PK)
- user_id → profiles.id (ON DELETE CASCADE)
- type (notification_type)
- title (text, NOT NULL)
- body (text, nullable)
- related_collaboration_id (uuid, nullable, → collaborations.id ON DELETE CASCADE)
- related_conversation_id (uuid, nullable, → conversations.id ON DELETE CASCADE)
- related_message_id (uuid, nullable, → messages.id ON DELETE CASCADE)
- is_read (boolean, default false)
- created_at (timestamptz)
- Users can only read/mark-read their own notifications
- Users cannot insert notifications directly (no INSERT policy for authenticated)

## 5. Triggers
- `create_conversation_on_accept()` — AFTER UPDATE on collaborations, when
  status transitions to 'accepted', creates exactly one conversation. Uses
  INSERT ... ON CONFLICT DO NOTHING to prevent duplicates.
- `notify_collab_request()` — AFTER INSERT on collaborations, creates a
  collaboration_request notification for the traveler.
- `notify_collab_accepted()` — AFTER UPDATE on collaborations, when status
  changes to 'accepted', creates a collaboration_accepted notification for
  the sender.
- `notify_collab_rejected()` — AFTER UPDATE on collaborations, when status
  changes to 'rejected', creates a collaboration_rejected notification for
  the sender.
- `notify_new_message()` — AFTER INSERT on messages, creates a new_message
  notification for the OTHER participant (not the sender).
- `update_conversation_last_message()` — AFTER INSERT on messages, updates
  conversations.last_message_at and conversations.updated_at.
- `guard_message_immutable()` — BEFORE UPDATE on messages, prevents changes
  to sender_id, conversation_id, created_at. Only allows read_at and
  message_text/updated_at changes.
- `conversation_set_updated_at()` — maintains updated_at on conversations.
- `message_set_updated_at()` — maintains updated_at on messages.

## 6. RLS — conversations
- SELECT: traveler_id = auth.uid() OR sender_id = auth.uid() OR is_admin()
- INSERT: NONE for authenticated (conversations created only by trigger/SECURITY DEFINER)
- UPDATE: traveler_id = auth.uid() OR sender_id = auth.uid() OR is_admin()
  (allows updating last_message_at, updated_at via triggers)
- DELETE: is_admin() only

## 7. RLS — messages
- SELECT: user is a participant in the conversation OR is_admin()
- INSERT: authenticated, sender_id = auth.uid(), user is a participant
- UPDATE: participant OR admin (trigger enforces immutability of ownership fields)
- DELETE: is_admin() only

## 8. RLS — notifications
- SELECT: user_id = auth.uid() OR is_admin()
- INSERT: NONE for authenticated (notifications created only by triggers)
- UPDATE: user_id = auth.uid() OR is_admin()
- DELETE: is_admin() only

## 9. Security Notes
- Conversations are auto-created by a SECURITY DEFINER trigger, not by clients
- Messages can only be sent by conversation participants
- Message ownership fields are immutable after creation
- Notifications are generated by database triggers, never by clients
- Users can only read and mark-read their own notifications
- No mock/seed data
*/

-- ============================================================
-- 1. ENUM
-- ============================================================

DO $$ BEGIN
  CREATE TYPE notification_type AS ENUM (
    'collaboration_request',
    'collaboration_accepted',
    'collaboration_rejected',
    'new_message'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ============================================================
-- 2. CONVERSATIONS TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS conversations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  collaboration_id uuid NOT NULL UNIQUE REFERENCES collaborations(id) ON DELETE CASCADE,
  traveler_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  sender_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  last_message_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_conv_traveler_id ON conversations (traveler_id);
CREATE INDEX IF NOT EXISTS idx_conv_sender_id ON conversations (sender_id);
CREATE INDEX IF NOT EXISTS idx_conv_last_message_at ON conversations (last_message_at DESC);

-- ============================================================
-- 3. MESSAGES TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sender_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  message_text text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  read_at timestamptz,
  CONSTRAINT msg_text_not_empty CHECK (btrim(message_text) <> ''),
  CONSTRAINT msg_text_max_length CHECK (length(message_text) <= 2000)
);

CREATE INDEX IF NOT EXISTS idx_msg_conversation_id ON messages (conversation_id);
CREATE INDEX IF NOT EXISTS idx_msg_sender_id ON messages (sender_id);
CREATE INDEX IF NOT EXISTS idx_msg_created_at ON messages (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_msg_read_at ON messages (read_at);

-- ============================================================
-- 4. NOTIFICATIONS TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  type notification_type NOT NULL,
  title text NOT NULL,
  body text,
  related_collaboration_id uuid REFERENCES collaborations(id) ON DELETE CASCADE,
  related_conversation_id uuid REFERENCES conversations(id) ON DELETE CASCADE,
  related_message_id uuid REFERENCES messages(id) ON DELETE CASCADE,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notif_user_id ON notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_notif_is_read ON notifications (user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_notif_type ON notifications (type);
CREATE INDEX IF NOT EXISTS idx_notif_created_at ON notifications (created_at DESC);

-- ============================================================
-- 5. TRIGGERS — CONVERSATIONS
-- ============================================================

-- updated_at for conversations
CREATE OR REPLACE FUNCTION conversation_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS conversation_updated_at ON conversations;
CREATE TRIGGER conversation_updated_at
  BEFORE UPDATE ON conversations
  FOR EACH ROW EXECUTE FUNCTION conversation_set_updated_at();

-- Auto-create conversation when collaboration is accepted
CREATE OR REPLACE FUNCTION create_conversation_on_accept()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Only fire when status transitions to 'accepted'
  IF OLD.status = 'pending' AND NEW.status = 'accepted' THEN
    INSERT INTO conversations (collaboration_id, traveler_id, sender_id)
    VALUES (NEW.id, NEW.traveler_id, NEW.sender_id)
    ON CONFLICT (collaboration_id) DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS collab_create_conversation ON collaborations;
CREATE TRIGGER collab_create_conversation
  AFTER UPDATE ON collaborations
  FOR EACH ROW EXECUTE FUNCTION create_conversation_on_accept();

REVOKE EXECUTE ON FUNCTION create_conversation_on_accept() FROM PUBLIC, anon, authenticated;

-- ============================================================
-- 6. TRIGGERS — COLLABORATION NOTIFICATIONS
-- ============================================================

-- Notify traveler when collaboration request is created
CREATE OR REPLACE FUNCTION notify_collab_request()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO notifications (user_id, type, title, body, related_collaboration_id)
  VALUES (
    NEW.traveler_id,
    'collaboration_request',
    'New collaboration request',
    'You have received a new collaboration request.',
    NEW.id
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS collab_notify_request ON collaborations;
CREATE TRIGGER collab_notify_request
  AFTER INSERT ON collaborations
  FOR EACH ROW EXECUTE FUNCTION notify_collab_request();

REVOKE EXECUTE ON FUNCTION notify_collab_request() FROM PUBLIC, anon, authenticated;

-- Notify sender when collaboration is accepted or rejected
CREATE OR REPLACE FUNCTION notify_collab_status_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF OLD.status = 'pending' AND NEW.status = 'accepted' THEN
    INSERT INTO notifications (user_id, type, title, body, related_collaboration_id)
    VALUES (
      NEW.sender_id,
      'collaboration_accepted',
      'Collaboration accepted',
      'Your collaboration request has been accepted.',
      NEW.id
    );
  ELSIF OLD.status = 'pending' AND NEW.status = 'rejected' THEN
    INSERT INTO notifications (user_id, type, title, body, related_collaboration_id)
    VALUES (
      NEW.sender_id,
      'collaboration_rejected',
      'Collaboration rejected',
      'Your collaboration request has been rejected.',
      NEW.id
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS collab_notify_status ON collaborations;
CREATE TRIGGER collab_notify_status
  AFTER UPDATE ON collaborations
  FOR EACH ROW EXECUTE FUNCTION notify_collab_status_change();

REVOKE EXECUTE ON FUNCTION notify_collab_status_change() FROM PUBLIC, anon, authenticated;

-- ============================================================
-- 7. TRIGGERS — MESSAGES
-- ============================================================

-- updated_at for messages
CREATE OR REPLACE FUNCTION message_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS message_updated_at ON messages;
CREATE TRIGGER message_updated_at
  BEFORE UPDATE ON messages
  FOR EACH ROW EXECUTE FUNCTION message_set_updated_at();

-- Guard: prevent changes to sender_id, conversation_id, created_at
CREATE OR REPLACE FUNCTION guard_message_immutable()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.sender_id <> OLD.sender_id THEN
    RAISE EXCEPTION 'Cannot change message sender_id';
  END IF;
  IF NEW.conversation_id <> OLD.conversation_id THEN
    RAISE EXCEPTION 'Cannot change message conversation_id';
  END IF;
  IF NEW.created_at <> OLD.created_at THEN
    RAISE EXCEPTION 'Cannot change message created_at';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS message_guard_immutable ON messages;
CREATE TRIGGER message_guard_immutable
  BEFORE UPDATE ON messages
  FOR EACH ROW EXECUTE FUNCTION guard_message_immutable();

REVOKE EXECUTE ON FUNCTION guard_message_immutable() FROM PUBLIC, anon, authenticated;

-- Update conversation last_message_at when a message is inserted
CREATE OR REPLACE FUNCTION update_conversation_on_message()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE conversations
  SET last_message_at = NEW.created_at,
      updated_at = now()
  WHERE id = NEW.conversation_id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS msg_update_conversation ON messages;
CREATE TRIGGER msg_update_conversation
  AFTER INSERT ON messages
  FOR EACH ROW EXECUTE FUNCTION update_conversation_on_message();

REVOKE EXECUTE ON FUNCTION update_conversation_on_message() FROM PUBLIC, anon, authenticated;

-- Notify the OTHER participant when a new message is sent
CREATE OR REPLACE FUNCTION notify_new_message()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  conv_traveler_id uuid;
  conv_sender_id uuid;
  recipient_id uuid;
BEGIN
  SELECT traveler_id, sender_id INTO conv_traveler_id, conv_sender_id
  FROM conversations WHERE id = NEW.conversation_id;

  -- Determine the recipient (the other participant)
  IF NEW.sender_id = conv_traveler_id THEN
    recipient_id := conv_sender_id;
  ELSIF NEW.sender_id = conv_sender_id THEN
    recipient_id := conv_traveler_id;
  ELSE
    RETURN NEW; -- sender is not a participant, shouldn't happen but safety
  END IF;

  INSERT INTO notifications (user_id, type, title, body, related_conversation_id, related_message_id)
  VALUES (
    recipient_id,
    'new_message',
    'New message',
    'You have received a new message.',
    NEW.conversation_id,
    NEW.id
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS msg_notify_recipient ON messages;
CREATE TRIGGER msg_notify_recipient
  AFTER INSERT ON messages
  FOR EACH ROW EXECUTE FUNCTION notify_new_message();

REVOKE EXECUTE ON FUNCTION notify_new_message() FROM PUBLIC, anon, authenticated;

-- ============================================================
-- 8. RLS — CONVERSATIONS
-- ============================================================

ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "conv_select" ON conversations;
CREATE POLICY "conv_select"
ON conversations FOR SELECT
TO authenticated
USING (
  auth.uid() = traveler_id
  OR auth.uid() = sender_id
  OR public.is_admin()
);

-- No INSERT policy for authenticated — conversations are created only by trigger
DROP POLICY IF EXISTS "conv_insert" ON conversations;
CREATE POLICY "conv_insert"
ON conversations FOR INSERT
TO authenticated
WITH CHECK (false);

DROP POLICY IF EXISTS "conv_update" ON conversations;
CREATE POLICY "conv_update"
ON conversations FOR UPDATE
TO authenticated
USING (
  auth.uid() = traveler_id
  OR auth.uid() = sender_id
  OR public.is_admin()
)
WITH CHECK (
  auth.uid() = traveler_id
  OR auth.uid() = sender_id
  OR public.is_admin()
);

DROP POLICY IF EXISTS "conv_delete" ON conversations;
CREATE POLICY "conv_delete"
ON conversations FOR DELETE
TO authenticated
USING (public.is_admin());

GRANT SELECT, UPDATE, DELETE ON conversations TO authenticated;

-- ============================================================
-- 9. RLS — MESSAGES
-- ============================================================

ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "msg_select" ON messages;
CREATE POLICY "msg_select"
ON messages FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM conversations c
    WHERE c.id = messages.conversation_id
    AND (c.traveler_id = auth.uid() OR c.sender_id = auth.uid())
  )
  OR public.is_admin()
);

DROP POLICY IF EXISTS "msg_insert" ON messages;
CREATE POLICY "msg_insert"
ON messages FOR INSERT
TO authenticated
WITH CHECK (
  auth.uid() = sender_id
  AND EXISTS (
    SELECT 1 FROM conversations c
    WHERE c.id = messages.conversation_id
    AND (c.traveler_id = auth.uid() OR c.sender_id = auth.uid())
  )
);

DROP POLICY IF EXISTS "msg_update" ON messages;
CREATE POLICY "msg_update"
ON messages FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM conversations c
    WHERE c.id = messages.conversation_id
    AND (c.traveler_id = auth.uid() OR c.sender_id = auth.uid())
  )
  OR public.is_admin()
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM conversations c
    WHERE c.id = messages.conversation_id
    AND (c.traveler_id = auth.uid() OR c.sender_id = auth.uid())
  )
  OR public.is_admin()
);

DROP POLICY IF EXISTS "msg_delete" ON messages;
CREATE POLICY "msg_delete"
ON messages FOR DELETE
TO authenticated
USING (public.is_admin());

GRANT SELECT, INSERT, UPDATE, DELETE ON messages TO authenticated;

-- ============================================================
-- 10. RLS — NOTIFICATIONS
-- ============================================================

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "notif_select" ON notifications;
CREATE POLICY "notif_select"
ON notifications FOR SELECT
TO authenticated
USING (
  auth.uid() = user_id
  OR public.is_admin()
);

-- No INSERT for authenticated — notifications created only by triggers
DROP POLICY IF EXISTS "notif_insert" ON notifications;
CREATE POLICY "notif_insert"
ON notifications FOR INSERT
TO authenticated
WITH CHECK (false);

DROP POLICY IF EXISTS "notif_update" ON notifications;
CREATE POLICY "notif_update"
ON notifications FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "notif_delete" ON notifications;
CREATE POLICY "notif_delete"
ON notifications FOR DELETE
TO authenticated
USING (public.is_admin());

GRANT SELECT, UPDATE, DELETE ON notifications TO authenticated;
